### ISSUE TITLE
Nefunkcne Cypress testy kvoli foreignIncome

### ISSUE THREAD

**Issue by Ormi** [slovensko-digital/priznanie-digital#791]
```
  Postpone cases
    1) basic
    2) foreignIncome


  0 passing (24s)
  2 failing

  1) Postpone cases
       basic:
     AssertionError: Timed out retrying after 8000ms: expected '\'Dňa\': Dátum nesmie byt vyšší ako 3 celé kalendárne mesiace  od konca zdaňovacieho obdobia uvedeného v úvode oznámenia' to be empty
      at Context.eval (webpack:///./cypress/e2e/executeCase.ts:423:50)

  2) Postpone cases
       foreignIncome:
     AssertionError: Timed out retrying after 8000ms: expected '\'Dňa\': Dátum nesmie byt vyšší ako 3 celé kalendárne mesiace  od konca zdaňovacieho obdobia uvedeného v úvode oznámenia' to be empty
      at Context.eval (webpack:///./cypress/e2e/executeCase.ts:423:50)
```

Chyby su zavisle jedna od druhej a ako napoveda datum je to kvoli neplatnemu postponeDate vo formulare FS.

"Datum nesmie byt vyssi ako 3 cele kalendarne mesiace od konca zdanovacieho obdobia uvedeneho v uvode oznamenia"

![cypress-screenshot](https://github.com/slovensko-digital/priznanie-digital/assets/3997725/749bfb4c-c561-44d6-92d2-dc40194f0091)

**Comment by Ormi** [comment]
Chcel som updatnut formular o odklad na novu verziu ale FS ho uz na webe nema, tak si musime pockat na dalsi rok.
